baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Show reading time in minutes for posts
  showReadingTime = false
  useRelativeCover = true

[languages]
  [languages.en]
    title = "Emruz Hossain"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Emruz Hossain"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "/skills"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "experiences"
        name = "Experiences"
        url = "/experiences"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/resume"
        weight = 5

# Run Site: hugo server
# Change In CSS:
#  yarn dev 
#  yarn build